name: piano-games
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - click=8.1.8=py39haa95532_0
  - colorama=0.4.6=py39haa95532_0
  - expat=2.7.3=h885b0b7_3
  - flask=2.2.5=py39haa95532_1
  - itsdangerous=2.2.0=py39haa95532_0
  - jinja2=3.1.6=py39haa95532_0
  - libexpat=2.7.3=h885b0b7_3
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.9.25=h716150d_1
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py39haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - astunparse==1.6.3
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - chex==0.1.90
      - contourpy==1.3.0
      - cycler==0.12.1
      - etils==1.5.2
      - flatbuffers==25.9.23
      - flax==0.8.5
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gast==0.7.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.14.0
      - humanize==4.13.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jax==0.4.30
      - jaxlib==0.4.30
      - keras==2.15.0
      - kiwisolver==1.4.7
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - msgpack==1.1.2
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.6.4
      - packaging==23.2
      - pandas==2.3.3
      - pillow==11.3.0
      - protobuf==4.25.8
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - scipy==1.13.1
      - setuptools==80.9.0
      - six==1.17.0
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.1
      - tensorflow-decision-forests==1.8.1
      - tensorflow-estimator==2.15.0
      - tensorflow-hub==0.16.1
      - tensorflow-intel==2.15.1
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflowjs==4.22.0
      - tensorstore==0.1.69
      - termcolor==3.1.0
      - tf-keras==2.15.1
      - toolz==1.1.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.6.0
      - werkzeug==3.1.4
      - wrapt==1.14.2
      - wurlitzer==3.1.1
      - zipp==3.23.0
prefix: C:\Users\sin06\miniconda3\envs\piano-games
